### ISSUE TITLE
iPic Mac App Store version: Share extension

### ISSUE THREAD

**Issue by JayBrown** [toolinbox/iPicUploader#5]
It would be great if the iPic MAS version had an .appex, an extension for the contextual "Share" menu, as imGuru has, and the discontinued ImageShareUr had.

That way you wouldn't need an app always sitting in the menu bar.

**Comment by atjason** [comment]
@JayBrown You can use system Services to update image via iPic, or Command + U shortcut, which can be modified.

**Comment by JayBrown** [comment]
Yes, I know, but the Services contextual menu is not always accessible, e.g. when clicking on an image in your browser. For that you need an extension: one right-click & select upload. Without it it's at least one step more complicated: one right-click, select "copy image", use the shortcut (or click on iPic & the pending image).

I also know you can (if possible) open the image in a new tab or window, and then drag it onto the menu icon, which is nice, but it only works, if iPic isn't tucked away in the Bartender bar.

**Comment by atjason** [comment]
I see. You can use the walk around way now.
