### ISSUE TITLE
The images only upload as JPEG?

### ISSUE THREAD

**Issue by devjoseluis** [toolinbox/iPicUploader#8]
Hello I was wondering how we can upload PNG transparent files with this library.

https://github.com/toolinbox/iPicUploader/blob/4d15817ab35c3a877c0ee40ce23cdeb8491bf254/iPicUploader/Classes/iPicUploadHelper.swift#L63

**Comment by atjason** [comment]
1. Could upload via file.
2. Modify the code, detect image type before send to iPic.

Note: Default Weibo image host doesn't support png. Need to use others like Imgur, S3, etc.
